In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('data/Student_Marks.csv')
print(data.head())
x = data.iloc[:, :2].to_numpy()
y = (data.iloc[:,2].to_numpy())
y = y.reshape(len(y), 1)

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299


In [3]:
x, y

x = np.array([[1,0],[1,1],[0,1],[0,0]])
y = np.array([[1],[0],[0],[1]])

In [4]:
def getRandomWeight(*r):
    # return np.random.randn(*r)
    return np.zeros(r) + 0.1

In [5]:
def forward(x, w, b):
    '''
    x -> each row is record
    w -> each column is each node's weight
    '''
    return np.dot(x, w) + b

In [6]:
# eg
x1 = np.array([
    [1,2], # 1st record
    [2,3], # 2nd record
    [4,5]  # 3rd record
])

w1 = np.array([
    [1,2], # 1st node weight
    [2,3], # 2nd node weight 
    [4,5]  # 3rd node weight
])

b1 = np.array([
    [1],
    [2],
    [3]
])

l1 = forward(x1, w1.T, b1)
print(l1)

w2 = np.array([
    [1,2,3]
])
b2 = np.array([1])
print(forward(l1, w2.T, b2))

[[ 6  9 15]
 [10 15 25]
 [17 26 44]]
[[ 70]
 [116]
 [202]]


In [7]:
def error(y, y_pred):
    return y - y_pred

In [ ]:
def gradient(w,b, x,err, lr=0.01):
    for i in range(len(x)):
        if i%2 ==0 :
            w = w - (x[i] * err[i] * lr)
            b = b - (lr * err[i])
    return w,b
    

In [ ]:
# ip -> 2 
# hidden -> 3
# op -> 1
# layer -> 2 x 3 x 1

ipw = getRandomWeight(3,2)
ipb = getRandomWeight(3,1)

hw = getRandomWeight(1,3)
hb = getRandomWeight(1)
print(ipw.shape, ipb.shape)
print(hw.shape, hb.shape)

(3, 2) (3, 1)
(1, 3) (1,)


In [12]:
for i in range(1):
    l1_op = forward(x,ipw.T, ipb.T)
    print(f'Level 1 op : {l1_op}')
    y_pred = forward(l1_op, hw.T, hb.T)
    print(f'Output : {y_pred}')
    # update outer weight
    oper = error(y,y_pred)
    print(f'Epoch : {i + 1}, Loss : {oper.mean()}')
    hw, hb = gradient(hw, hb, l1_op,oper)
    # update inner weight
    hierr =  ipw * oper
    print(f'Hidden Error : {hierr}')
    # ipw, ipb = gradient(ipw, ipb, x, err)

Level 1 op : [[0.2 0.2 0.2]
 [0.3 0.3 0.3]
 [0.2 0.2 0.2]
 [0.1 0.1 0.1]]
Output : [[0.1445974 ]
 [0.17377226]
 [0.1445974 ]
 [0.11542254]]
Epoch : 1, Loss : 0.3554025984


KeyboardInterrupt: 