In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('data/Student_Marks.csv')
print(data.head())
x = data.iloc[:, :2].to_numpy()
y = (data.iloc[:,2].to_numpy())
y = y.reshape(len(y), 1)

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299


In [3]:
x, y

(array([[3.   , 4.508],
        [4.   , 0.096],
        [4.   , 3.133],
        [6.   , 7.909],
        [8.   , 7.811],
        [6.   , 3.211],
        [3.   , 6.063],
        [5.   , 3.413],
        [4.   , 4.41 ],
        [3.   , 6.173],
        [3.   , 7.353],
        [7.   , 0.423],
        [7.   , 4.218],
        [3.   , 4.274],
        [3.   , 2.908],
        [4.   , 4.26 ],
        [5.   , 5.719],
        [8.   , 6.08 ],
        [6.   , 7.711],
        [8.   , 3.977],
        [4.   , 4.733],
        [6.   , 6.126],
        [5.   , 2.051],
        [7.   , 4.875],
        [4.   , 3.635],
        [3.   , 1.407],
        [7.   , 0.508],
        [8.   , 4.378],
        [5.   , 0.156],
        [4.   , 1.299],
        [8.   , 3.864],
        [3.   , 1.923],
        [8.   , 0.932],
        [6.   , 6.594],
        [3.   , 4.083],
        [3.   , 7.543],
        [4.   , 2.966],
        [6.   , 7.283],
        [7.   , 6.533],
        [6.   , 7.775],
        [4.   , 0.14 ],
        [6.   , 

In [4]:
def getRandomWeight(*r):
    return np.random.randn(*r)
    # return np.zeros(r) + 0.1

In [5]:
def forward(x, w, b):
    '''
    x -> each row is record
    w -> each column is each node's weight
    '''
    return np.dot(x, w) + b

In [6]:
# eg
x1 = np.array([
    [1,2], # 1st record
    [2,3], # 2nd record
    [4,5]  # 3rd record
])

w1 = np.array([
    [1,2], # 1st node weight
    [2,3], # 2nd node weight 
    [4,5]  # 3rd node weight
])

b1 = np.array([
    [1],
    [2],
    [3]
])

l1 = forward(x1, w1.T, b1)
print(l1)

w2 = np.array([
    [1,2,3]
])
b2 = np.array([1])
print(forward(l1, w2.T, b2))

[[ 6  9 15]
 [10 15 25]
 [17 26 44]]
[[ 70]
 [116]
 [202]]


In [7]:
def error(y, y_pred):
    return y - y_pred

In [8]:
# ip -> 2 
# hidden -> 3
# op -> 1
# layer -> 2 x 3 x 1

ipw = getRandomWeight(3,2)
ipb = getRandomWeight(3,1)

hw = getRandomWeight(1,3)
hb = getRandomWeight(1)
print(ipw.shape, ipb.shape)
print(hw.shape, hb.shape)

(3, 2) (3, 1)
(1, 3) (1,)


In [24]:
for i in range(10):
    l1_op = forward(x,ipw.T, ipb.T)
    y_pred = forward(l1_op, hw.T, hb)
    print(error(y,y_pred).mean())

25.936520326588163
25.936520326588163
25.936520326588163
25.936520326588163
25.936520326588163
25.936520326588163
25.936520326588163
25.936520326588163
25.936520326588163
25.936520326588163


In [21]:
#np.dot(ipw.T, x[0])
ipw.T, x[0], ipb

(array([[-1.2251147 , -1.51682611,  1.13029239],
        [-0.76273057,  0.10337021, -0.48097079]]),
 array([3.   , 4.508]),
 array([[-0.47490657],
        [-0.30143318],
        [ 0.30784389]]))

In [22]:
np.dot(x[0],ipw.T) + ipb.T

array([[-7.58864005, -4.38591861,  1.53050473]])